### ISSUE TITLE
Problem with accessing the repository

### ISSUE THREAD

**Issue by samiscoding** [RMLio/RMLStreamer#1]
I'm trying to clone RMLStreamer  (git clone ssh://git@git.datasciencelab.ugent.be:4444/rml/rml-streamer.git) but seems the permission is denied due to publickey. I also tried via HTTPS protocol which failed since the password is not provided. Any tips for accessing?

**Comment by pheyvaer** [comment]
Hi @samiscoding,

That is an old link. Sorry about that. We will update the README. To clone the repo, you can use the url of this Github repo: `git@github.com:RMLio/RMLStreamer.git`

**Comment by samiscoding** [comment]
Thanks. Could you also please provide info about the version of maven and scala? Because I already cloned from git repository but have problem with installing using maven (mvn clean install), seems to be maven plugins error that I suspect that is due to the conflicts between the versions.

**Comment by ghsnd** [comment]
The code as it was, didn't build properly on some systems. That's fixed now, so `mvn clean package` or `mvn clean install` should work. If not, please reopen this issue.

FYI, to build you need maven 3. The build automatically pulls Scala 2.11, so there is no need to have it installed. It also shouldn't conflict with existing Scala installations.
