### ISSUE TITLE
Slf4j conflicts error when running through Docker

### ISSUE THREAD

**Issue by vemonet** [RMLio/RMLStreamer#10]
I am trying to deploy the RMLStreamer using the [following instructions](https://github.com/RMLio/RMLStreamer/tree/master/docker), but I am facing an error which seems to be due to conflict with log libraries:

```
ERROR be.ugent.rml.cli.Main                                         - org.slf4j.impl.Log4jLoggerAdapter cannot be cast to ch.qos.logback.classic.Logger
java.lang.ClassCastException: org.slf4j.impl.Log4jLoggerAdapter cannot be cast to ch.qos.logback.classic.Logger
	at be.ugent.rml.cli.Main.setLoggerLevel(Main.java:343)
	at be.ugent.rml.cli.Main.main(Main.java:150)
	at be.ugent.rml.cli.Main.main(Main.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:576)
```

I tried to exclude slf4j from the pom.xml : 
```xml
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

But it didn't help. Do you have an idea how it can be resolved? Do you experiment the same issue on your side?

Thanks

**Comment by ghsnd** [comment]
It seems like you deployed a jar from [RMLMapper](https://github.com/RMLio/rmlmapper-java), not RMLStreamer. Could you try again with the ([latest release](https://github.com/RMLio/RMLStreamer/releases/latest)) of RMLStreamer?

**Comment by vemonet** [comment]
Thanks, sorry I did not noticed I mixed the jar

It works much better with the right jar

fyi: I integrated the RMLStreamer to a Command Line Interface tool we are working on. It is a first draft and will need some improvements, but it works quite well on Docker from the command line

It aims to help with the orchestration of services allowing to deploy a triplestore, populate it and deploy services over it (SPARQL, LDF server, linked data browser, HTTP OpenAPI)

Thanks a lot for this tool

**Comment by ghsnd** [comment]
> fyi: I integrated the RMLStreamer to a Command Line Interface tool we are working on. It is a first draft and will need some improvements, but it works quite well on Docker from the command line.

Cool, keep me posted about this CLI tool!
