### ISSUE TITLE
Syntax error in run.sh

### ISSUE THREAD

**Issue by pheyvaer** [RMLio/RMLStreamer#12]
A `)` is missing at the end of https://github.com/RMLio/RMLStreamer/blob/master/run.sh#L98

**Comment by ghsnd** [comment]
Hi @pheyvaer, `run.sh` has been removed since version 2.0.0 because one can directly use the `flink` binary, as described [here](https://github.com/RMLio/RMLStreamer#executing-rml-mappings).
