### ISSUE TITLE
"Error while parsing JSON" issue when calling RMLStreamer as a Lenses.io Kafka topic consumer

### ISSUE THREAD

**Issue by GenEars** [RMLio/RMLStreamer#29]
Dear RMLStreamer team,
I get an odd issue when calling RMLStreamer as a Kafka topic consumer (see flink log below):
```
021-06-06 15:28:27,889 ERROR io.rml.framework.core.item.json.JSONItem$                    [] - Error while parsing JSON:
```
... followed by some unprintable data around correct values from the topic.

The mapping is done this way (see snippet below) upon the Lenses IO Box demo dataset (see https://docs.lenses.io/4.1/tools/box/) :
```
   rml:logicalSource [
       rml:source [
           rdf:type rmls:KafkaStream ;
           rmls:broker "localhost:9092" ;
           rmls:groupId "0";
           rmls:topic "sea_vessel_position_reports" ;
       ];
       rml:referenceFormulation ql:JSONPath ;
   ];

[...]

   rr:predicateObjectMap [
     rr:predicate :hasSpeed;
     rr:objectMap [
       rml:reference "$.Speed"
     ]
   ];

[...]
```

The same issue occurs with other topics of my own.
My guess is that there's some charset issue or I'm missing something with the rml or rmls specification.
For sure the issue is not about RMLStreamer connecting to the Kafka Broker as some data is pulled (though not correctly parsed).

Do you have any piece of advice or documentation to provide ?
Best regards,
LTa.

**Comment by GenEars** [comment]
Hi,
In addition to my previous comment, I noticed that::
1. Calling RMLStreamer with source:KafkaStream always leads to the following stdout
```
$FLINK_BIN run ./RMLStreamer-2.1.2-SNAPSHOT.jar toFile -o /tmp/rmlstreamer_out.nt -m //tmp/rmlstreamer_mapping.ttl
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.flink.api.java.ClosureCleaner (file:/~/.local/flink-1.12.3/lib/flink-dist_2.11-1.12.3.jar) to field java.util.Properties.serialVersionUID
WARNING: Please consider reporting this to the maintainers of org.apache.flink.api.java.ClosureCleaner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Job has been submitted with JobID 27a364cb09a5a43c2b567c8e0b243204
```
2. There's no running issue about JSON parsing with the example provided in  RMLStreamer/docker/scenario-1/mapping.ttl 

... I look forward for any solution.

**Comment by ghsnd** [comment]
Hi,

Let me first answer on the WARNING messages. These are related to Flink running on a JVM version > 8 and can be ignored. It is perfectly safe to use a JVM version up to 14 to run RMLStreamer (although we develop and test on 11).

Concerning the JSON error: the Lenses IO Box demo uses AVRO serialisation to send messages over Kafka. RMLStreamer only supports String serialisation at the moment. While we are not immediately planning to implement this, we try to help where we can as much as possible.
If you have any concrete suggestions, we welcome pull requests ([code](https://github.com/RMLio/RMLStreamer/blob/592793b28224512cfffcda3fd3dacc7ff94440e5/src/main/scala/io/rml/framework/flink/source/JSONStream.scala#L69) where the serialisation is set) and try to handle them as swiftly as we can manage.
However, we are also very open to discuss other kinds of collaboration possibilities,
so we can plan and dedicate time to any specific request.
If the latter is of your interest, don't hesitate to reach out by sending an e-mail to info@rml.io.

**Comment by GenEars** [comment]
Hi @ghsnd 
Many thanks for the insights.

So current options are:
* Use an other kafka platform,
* Improve RMLStreamer for Avro compatibilty (thus this issue should be renamed « make RMLStreamer compatible with Avro » 😉),
* Use a custom Kafka lenses deserializer as discussed in https://docs.lenses.io/2.1/lenses-sql/protobuf.html

Let me check my options before taking any direction.

Again, thanks. You may close the issue if you think it is ok with it.

**Comment by GenEars** [comment]
... ok, here are my current thoughts about this improvement:
* One may wish to make Lenses.io provide JSON data as topic output: I tried some configs from [SQL_CheatSheet.pdf](https://lenses.io/resources/SQL_CheatSheet.pdf) and [data-format](https://help.lenses.io/using-lenses/data/data-formats/) but I was not successful (yet ?)
* Or change the [code](https://github.com/RMLio/RMLStreamer/blob/592793b28224512cfffcda3fd3dacc7ff94440e5/src/main/scala/io/rml/framework/flink/source/JSONStream.scala#L69) you provided with help from [Flink Kafka Connector](https://ci.apache.org/projects/flink/flink-docs-master/docs/connectors/datastream/kafka/), [AvroDeserializationSchema.java example](https://github.com/okkam-it/flink-examples/blob/master/src/main/java/org/okkam/flink/avro/AvroDeserializationSchema.java) and [how-to-deserialize-avro-messages-from-kafka-in-flink-scala](https://stackoverflow.com/questions/55128833/how-to-deserialize-avro-messages-from-kafka-in-flink-scala), which means:
  1. provide a property about where to find the custom (compiled) `AvroDeserializationSchema` class (see [how-to-decode-kafka-messages-using-avro-and-flink](https://stackoverflow.com/questions/38715286/how-to-decode-kafka-messages-using-avro-and-flink))
  2. Adapt [code](https://github.com/RMLio/RMLStreamer/blob/592793b28224512cfffcda3fd3dacc7ff94440e5/src/main/scala/io/rml/framework/flink/source/JSONStream.scala#L69) so that it refers to the AvroDeserializationSchema instance if relevant, or keeps refering to `SimpleStringSchema()` otherwise.
  3. compile the RMLStreamer with a `flink-avro` dependency (see [connectors/datastream/kafka](https://ci.apache.org/projects/flink/flink-docs-master/docs/connectors/datastream/kafka/)).

I am not equipped to go over option n°2 ... so I leave it to the community as of now.

**Comment by ghsnd** [comment]
Hi,

The  `sea_vessel_position_reports` topic keeps containing avro messages because the `ais-receiver` app which generates the data (http://127.0.0.1:3030/data/apps/details/external/ais-receiver/monitor if you run locally) produces avro messages. I don't see immediately how to change that.

For what it's worth: I see the `backblaze_smart` topic in the Lenses.io demo box contains plaintext JSON messages. You could use that as is to test...

**Comment by GenEars** [comment]
Hi @ghsnd ,
I had, yesterday, an interesting talk with lenses.io about this.
If you can manage the source connector's configuration, then adding the following commands allows to force the Kafka for storing and sending JSON data:
```
key.converter=org.apache.kafka.connect.json.JsonConverter 
value.converter=org.apache.kafka.connect.json.JsonConverter 
```
I also agree with you about the `sea_vessel_position_reports`.
Thanks for pointing out the `backblaze_smart`; I will run some test on this topic next week and report back...

**Comment by GenEars** [comment]
Hi @ghsnd ,
I took some time this evening with the `backblaze_smart` with some mixed results:

the FLINK job starts, receive records but sends nothing out (Bytes Sent = 0 + my MQTT subscriber sees nothing although my MQTT broker corectly sees the FLINK job connection).

Here's my RML config:
```
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix ex: <http://example.com/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix rmls: <http://semweb.mmlab.be/ns/rmls#> .
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .

<TriplesMap1> a rr:TriplesMap;

   rml:logicalSource [
       rml:source [
           rdf:type rmls:KafkaStream ;
           rmls:broker "localhost:9092" ;
           rmls:groupId "0";
           rmls:topic "backblaze_smart" ;
       ];
       rml:referenceFormulation ql:JSONPath ;
   ];

   rr:subjectMap [
	rml:reference "$.serial_number";
        rr:termType rr:IRI;
        rr:class ex:SerialNumber

   ].
```
... and how I run it:
```
$FLINK_BIN run ./RMLStreamer-2.1.2-SNAPSHOT.jar toMQTT -b 127.0.0.1:1883 -t rml -m ./rmlstreamer_back_blaze_smart_01.ttl
```

Some questions:
* Is it a JSON Path issue ?
* Is it a RML issue ?
* Is it linked to how Kafka sends the JSON data ? (b.t.w could we ask RMLStreamer to provide verbose logs into FLINK so we could see the received records ?)

Best.

PS: I had the same mixed result with other topics of my own with JSON data.

**Comment by GenEars** [comment]
Hi @ghsnd 
After some successful experiments I did on my own data with *lenses.io/Kafka* and *RMLStreamer*, I tried again *RMLStreamer-2.1.2* with the `backblaze_smart` topic.

Processing is now ok :checkered_flag: 

Things that I changed since my last message:
* Update to Lenses version 4.3.4 => jSon syntax parsing error got away,
* Use other references within jSonPATH (see example below) => mapping gets ok.

RML config (excerpt):
```
rr:subjectMap [ rr:template "http://example.com/model/{model}" ];

rr:predicateObjectMap [
  rr:predicate rdf:type;
  rr:objectMap [ rr:constant ex:Model ];
];

rr:predicateObjectMap [
  rr:predicate ex:hasSerialNumber;
  rr:objectMap [ rml:reference "serial_number" ];
].
```

Testings were run for the two following tool chains:
* (Kafka lenses.io backblaze_smart)=[RMLStreamer]=>(nquad file)
* (Kafka lenses.io backblaze_smart)=[RMLStreamer]=>(MQTT)

As there's no more processing fault and mapping problem, I close the issue.
