### ISSUE TITLE
issue in object map with functions: malformed IRI

### ISSUE THREAD

**Issue by giorgialodi** [RMLio/RMLStreamer#33]
Hi guys @bjdmeest @gertjandemulder 

I am trying to use the RML streamer but I am encountering a set of issues.
One of these issues is the following.

I need to define a triple which is < subject > predicate < object > where object is not a literal but a URI.
In order to construct the URI of the object, i need to invoke a function that returns rr:termType rr:IRI. The result is the following: < subject > predicate <"object">; so the URI is between <> and "" which is very strange.

To be more precise, an example is the following:

- the input CSV file 
```
field1,field2
A,B
``` 
- the mapping file

```
<#LogicalSourceCSV> a rml:BaseSource ;
      rml:source  "input.csv";
      rml:referenceFormulation ql:CSV .

<#dataMapping> a rr:TriplesMap ;
      rml:logicalSource <#LogicalSourceCSV> ;

      rr:subjectMap [
          rr:template "https://example.org/subject/{field1}";
      ];
      rr:predicateObjectMap [
         rr:predicate <https://example.org/predicate> ;
         rr:objectMap <#functionMapping>
      ] .

<#functionMapping>
     rr:termType rr:IRI ;
     fnml:functionValue [
     rr:predicateObjectMap [
         rr:predicate fno:executes ;
         rr:objectMap [ rr:constant grel:toLowerCase ]
     ];
     rr:predicateObjectMap [
        rr:predicate grel:valueParameter ;
        rr:objectMap [ rr:template "https://example.org/object/{field2}" ; rr:termType rr:IRI ]
     ]
] .
```

The output is the following:
`<https://example.org/subject/A> <https://example.org/predicate> <"https://example.org/object/b"> .`

The quotes in the output are strange. So it seems that it recognises the URI of the object but it puts the value between quotes.

In the RMLMapper the same code works perfectly. 

Could you please help me to fix that URI? Thanks a lot!

**Comment by gertjandemulder** [comment]
@giorgialodi , we are looking into it, and will come back to you! :) 
Kind regards,
G

**Comment by giorgialodi** [comment]
Hi @gertjandemulder thanks a lot!
