### ISSUE TITLE
testing the streamer

### ISSUE THREAD

**Issue by vchaudhri** [RMLio/RMLStreamer#50]
I am trying to follow the instructions to test out the stream, and the documentation states:

Once the input and output ports are listened to by applications or by the above commands, the RML Mapping can be executed. RMLStreamer will open the input and output sockets so it can act upon data that will be written to the input socket.

Whenever data is written (every data object needs to end with \n) to the socket, this data will be processed by the RML Framework.

Could you please provide an example of how to write the data to the socket?

(I did write a python program to send data to the socket, but it crashes the mapper.  I'd prefer to use test code that you have used to test it.)

**Comment by ghsnd** [comment]
There's an eample in the README, using netcat (nc) to send and receive data. The sender is started like so:
```
nc -lk 5005 # This will start listening for input connections at port 5005
```
However, this requires you to type (paste) data in the console where this command is started.
You can easily test sending a file with e.g.
```
cat yourfile | nc -lk 5005
```

If you send data (with Python) and the mapper crashes, it received something. Is it possible to paste the (error) log? If you run it on a Flink cluster the log file is probably in `$FLINK_HOME/log`.

**Comment by vchaudhri** [comment]
Where does it place the log if I simply run it using command line as suggested in: 

$java run rmstream.jar  toTCPSocket -s localhost:9000 -m .../framework/src/main/resources/json_stream_data_mapping.ttl

And how could I send the log to a specific location?

**Comment by ghsnd** [comment]
RMLStreamer tries to connect to two TCP "servers", listening for incoming connections. One for the input, one for the output.
Important to note is that RMLStreamer does *not* listen, but tries to *connect* to your service(s).

Let's take [this example](https://github.com/RMLio/RMLStreamer/tree/development/src/test/resources/stream/tcp/RMLTC0001a-CSV-STREAM-TCP).

First, we start a TCP server listening for output connections on port 5005; RMLStreamer will write to this one:
```
nc -l 5005
```

Second, in another terminal, we start a TCP server that RMLStreamer connects to to retrieve data (the port is also defined in the mapping file):
```
nc -l 9999 < datasource.csv
```

Third, we run RMLStreamer now that the two sockets are listening:

```
java -jar RMLStreamer-v2.5.0-standalone.jar toTCPSocket -m mapping.ttl -s localhost:5005
```

Now end the input stream by hitting Ctrl-C in the second terminal (with netcat listening on 9999).
Now an EOF gets sent causing RMLStreamer to process the message.

The output will appear on the second terminal (on port 5005), and RMLStreamer will exit because the input connection is terminated.

Working with the standalone version of RMLStreamer 
([download](https://github.com/RMLio/RMLStreamer/releases/download/v2.5.0/RMLStreamer-v2.5.0-standalone.jar)) 
allows you to run it just as a Java program.
Logging goes to stdout, but can be configured using Log4J config.

In your case, you will have to create listening sockets in your python app.

When using TCP sockets, RMLStreamer considers an empty line (so just `\n`)as a message separator.

Hope this helps a bit...

**Comment by vchaudhri** [comment]
Thanks for your helpful guidance.  I am now able to set  it up exactly the way it is described in the documentation and follow the exact steps outlined by you in your comment above. For a small test case shown in test.json, it gets correctly translated by rmlmapper and rmlstreamer when run in the command line mode, but when it is run through the TCP Socket streams, it produces the error shown in the log.  I have also included the sample mapping file. Could you please advise if you are able to reproduce it and the way to fix it?

====test.json=====
`{
  "Id":"foo",
  "Properties":
  {
    "pid":"bar"
  }
}
`
====ex2-stream.ttl mapping rules =====
`@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@base <http://example.com/ns#>.
@prefix g:  <http://g.j.net/s#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rmls: <http://semweb.mmlab.be/ns/rmls#>.




<#VenueMapping> a rr:TriplesMap;
                rml:logicalSource [
                                    rml:source [
                                                 rdf:type rmls:TCPSocketStream ;
                                                 rmls:hostName "localhost";
                                                 rmls:port "5005"
                                               ];
                                    rml:referenceFormulation ql:JSONPath;
    rml:iterator "$"
  ]; 

  rr:subjectMap [
    rr:template "https://myaccess20-api.dev.aws.jpmchase.net/grant#{Id}";
    rr:class g:Agent
  ];

  rr:predicateObjectMap [
    rr:predicate g:pid;
    rr:objectMap [
      rml:reference "Properties.pid"
    ]
  ].

`
====Error output from the rmlstreamer ======
d601430@T2RXRMFWKH rml % java -jar RMLStreamer-v2.5.0-standalone.jar toTCPSocket -s localhost:9000 -m  /Users/d601430/Desktop/rml/ex2-stream.ttl
15:12:12,627 INFO  io.rml.framework.Main$                                        - Mapping file: /Users/d601430/Desktop/rml/ex2-stream.ttl
Job name: RMLStreamer
Base IRI: /
Parallelise over local task slots: true
Maximum parallelism: None
Post processor: None
Checkpoint interval: /
Auto Watermark interval: 50
Output method: Socket
Output file: /
Kafka broker list: /
Kafka topic: /
Kafka topic partition id: /
Output TCP socket: localhost:9000
Function description locations: None
Discard output: false
Number of standard stream triple maps: 0
Total extracted std triple maps: 0
Number of standard stream triple maps: 1
Total extracted std triple maps: 1
15:12:12,971 INFO  io.rml.framework.Main$                                        - Datastream Job found.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.flink.api.java.ClosureCleaner (file:/Users/d601430/Desktop/rml/RMLStreamer-v2.5.0-standalone.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.apache.flink.api.java.ClosureCleaner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
15:12:13,016 INFO  io.rml.framework.Main$                                        - 1 Triple Maps are found.
15:12:15,204 WARN  org.apache.flink.runtime.webmonitor.WebMonitorUtils           - Log file environment variable 'log.file' is not set.
15:12:15,204 WARN  org.apache.flink.runtime.webmonitor.WebMonitorUtils           - JobManager log files are unavailable in the web dashboard. Log file location not found in environment variable 'log.file' or configuration key 'web.log.path'.
15:12:41,023 ERROR io.rml.framework.core.item.json.JSONItem$                     - Error while parsing JSON:
  "Properties":
15:12:41,025 ERROR io.rml.framework.core.item.json.JSONItem$

**Comment by ghsnd** [comment]
Do you send the complete JSON file/object in one line or pretty-printed over multiple lines? The latter won't work because a newline will be seen as new JSON input. I just tried it in one line and the output is:
```
<https://myaccess20-api.dev.aws.jpmchase.net/grant#foo> <http://g.j.net/s#pid> "bar" .
<https://myaccess20-api.dev.aws.jpmchase.net/grant#foo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://g.j.net/s#Agent> .
```

**Comment by vchaudhri** [comment]
Yes that resolves the problem. Thank you very much for your follow up.
