### ISSUE TITLE
Mixed input (dataset and datastream)

### ISSUE THREAD

**Issue by Felixpacher** [RMLio/RMLStreamer#61]
Hello, I am using RMLStreamer with an XML-file as input as well as an MQTT stream. The mapping works, but only the streaming data gets mapped with every new data instance. Justthe ParentTriplesMap of the mapping of the stream with the TriplesMap of the static data works. The rest is not mapped. Is this the intended way of mapping mixed input or is there a way to execute the whole mapping every time the streaming input data changes?

Thank you very much in advance for your answer.

**Comment by s-minoo** [comment]
[line 427](https://github.com/RMLio/RMLStreamer/blob/development/src/main/scala/io/rml/framework/Main.scala#L427) 
indicates that the parent triples map has to be a static data source. @ghsnd  can you confirm it ?

**Comment by ghsnd** [comment]
Yes, the other way around is not implemented.

**Comment by Felixpacher** [comment]
Thank you for your answers!
